import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('processed_student_performance.csv')
plt.style.use('ggplot')
plt.bar(df['Student'], df['Final_Score'], color='magenta')
plt.xlabel('Name')
plt.ylabel('Final Score')
plt.title('List of Scores')
plt.xticks(fontsize=6)
plt.show()
plt.scatter(df['Hours_Studied'],df['Final_Score'],alpha=0.6)
plt.xlabel('Hours Studied')
plt.ylabel('Final Score')
plt.title('Input and Output')
plt.show()
plt.hist(df['Final_Score'], bins=30, color='green')
plt.xlabel('Final Score')
plt.ylabel('Frequency')
plt.title('Distribution of Final Scores')
plt.show()
plt.scatter(df['Previous_Score'],df['Improvement'],alpha=0.5)
plt.xlabel('Previous_Score')
plt.ylabel('Improvement')
plt.title('Current vs future performance')
plt.show()